# Generated by Django 4.2.25 on 2026-08-29 11:05

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='identifiant URL')),
                ('kind', models.CharField(choices=[('realized', 'Réalisation'), ('concept', 'Concept créatif')], default='realized', max_length=16, verbose_name='type de projet')),
                ('title_fr', models.CharField(max_length=160, verbose_name='titre (FR)')),
                ('title_de', models.CharField(blank=True, max_length=160, verbose_name='titre (DE)')),
                ('subtitle_fr', models.CharField(blank=True, max_length=200, verbose_name='sous-titre (FR)')),
                ('subtitle_de', models.CharField(blank=True, max_length=200, verbose_name='sous-titre (DE)')),
                ('summary_fr', models.TextField(blank=True, verbose_name='résumé (FR)')),
                ('summary_de', models.TextField(blank=True, verbose_name='résumé (DE)')),
                ('story_fr', models.TextField(blank=True, help_text='Séparez les paragraphes par une ligne vide.', verbose_name='texte long (FR)')),
                ('story_de', models.TextField(blank=True, verbose_name='texte long (DE)')),
                ('event_type_fr', models.CharField(blank=True, max_length=120, verbose_name="type d'événement (FR)")),
                ('event_type_de', models.CharField(blank=True, max_length=120, verbose_name="type d'événement (DE)")),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='lieu')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='année')),
                ('keywords_fr', models.CharField(blank=True, help_text='Séparés par des virgules.', max_length=240, verbose_name='mots-clés (FR)')),
                ('keywords_de', models.CharField(blank=True, max_length=240, verbose_name='mots-clés (DE)')),
                ('cover', models.ImageField(upload_to='projects/covers/', verbose_name='image de couverture')),
                ('is_featured', models.BooleanField(default=False, verbose_name="mis en avant sur l'accueil")),
                ('is_published', models.BooleanField(default=True, verbose_name='publié')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ['order', '-created_at'],
            },
            bases=(core.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='nom et prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='adresse e-mail')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='téléphone')),
                ('preferred_language', models.CharField(default='Français', max_length=20, verbose_name='langue souhaitée')),
                ('event_type', models.CharField(blank=True, max_length=80, verbose_name="type d'événement")),
                ('event_date', models.DateField(blank=True, null=True, verbose_name="date de l'événement")),
                ('event_location', models.CharField(blank=True, max_length=180, verbose_name="lieu de l'événement")),
                ('guest_count', models.CharField(blank=True, max_length=60, verbose_name="nombre d'invités")),
                ('services', models.TextField(blank=True, verbose_name='prestations souhaitées')),
                ('theme', models.CharField(blank=True, max_length=250, verbose_name='thème ou palette')),
                ('budget', models.CharField(blank=True, max_length=60, verbose_name='budget')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('referral', models.CharField(blank=True, max_length=80, verbose_name='comment nous a connus')),
                ('consent', models.BooleanField(default=False, verbose_name='consentement RGPD')),
                ('submitted_language', models.CharField(default='fr', max_length=5, verbose_name='langue du formulaire')),
                ('forwarded_to_google', models.BooleanField(default=False, verbose_name='transmis au Google Form')),
                ('forward_error', models.TextField(blank=True, verbose_name='erreur de transmission')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('in_progress', 'En cours'), ('quoted', 'Devis envoyé'), ('won', 'Confirmée'), ('closed', 'Classée')], default='new', max_length=16, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='reçue le')),
            ],
            options={
                'verbose_name': 'demande de devis',
                'verbose_name_plural': 'demandes de devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='image')),
                ('stage', models.CharField(choices=[('moodboard', 'Moodboard'), ('details', 'Détails'), ('setup', 'Installation'), ('result', 'Résultat final')], default='result', max_length=16, verbose_name='étape')),
                ('caption_fr', models.CharField(blank=True, max_length=200, verbose_name='légende (FR)')),
                ('caption_de', models.CharField(blank=True, max_length=200, verbose_name='légende (DE)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project')),
            ],
            options={
                'verbose_name': 'image de projet',
                'verbose_name_plural': 'images de projet',
                'ordering': ['order', 'id'],
            },
            bases=(core.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaletteColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(help_text='#4A1220', max_length=7, verbose_name='code couleur')),
                ('name', models.CharField(blank=True, max_length=60, verbose_name='nom')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palette', to='core.project')),
            ],
            options={
                'verbose_name': 'couleur de palette',
                'verbose_name_plural': 'palette',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InspirationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspirations/%Y/%m/', verbose_name="photo d'inspiration")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspirations', to='core.quoterequest')),
            ],
            options={
                'verbose_name': "photo d'inspiration",
                'verbose_name_plural': "photos d'inspiration",
                'ordering': ['id'],
            },
        ),
    ]
