# Generated by Django 4.2.25 on 2026-08-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('logo', 'Logo (en-tête, pied de page, favicon)'), ('hero', "Grande image de l'accueil"), ('portrait', 'Portrait — page À propos'), ('atmosphere', 'Ambiance — page À propos'), ('share', 'Image de partage (réseaux sociaux)')], help_text="Chaque emplacement ne peut recevoir qu'une seule image.", max_length=24, unique=True, verbose_name='emplacement')),
                ('image', models.ImageField(upload_to='site/', verbose_name='image')),
                ('alt_fr', models.CharField(blank=True, help_text="Description de l'image pour l'accessibilité et le référencement.", max_length=200, verbose_name='texte alternatif (FR)')),
                ('alt_de', models.CharField(blank=True, max_length=200, verbose_name='texte alternatif (DE)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mise à jour le')),
            ],
            options={
                'verbose_name': 'image du site',
                'verbose_name_plural': 'images du site',
                'ordering': ['slot'],
            },
        ),
    ]
